### ISSUE TITLE
Differential builds for each PR on travis

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#136]
The approach ideal is using the git differential like [codecov](http://codecov.io/) does. We need to figure out how we can make this happens yet. That changes should reflect and we need changing the `stats.py` and `stats.exs` to receive the files to test optionally (or from `stdin` to the solution can be piped).

The discussion about that was made here #135

# Roadmap

- [x] script for given the ref of PR return the filepaths of the files change using only `git` and shell script
- [x] change `stats.py` to receive optionally the filepaths instead to given by the flags `-s` and `--search`
- [ ] same as above but for the Elixir asynchronous version on `stats.exs`
- [x] integrate that solution to .travis.yml

**Comment by lubien** [comment]
I'm pretty sure we can do something like `git diff master other_branch --name-only` to get which files changed.

Travis does provide the current branch name and also has an env that says that it's currently building an PR so the diff is a way to go.

You would just have to get filenames of solutions from that command and test them.

**Comment by ryukinix** [comment]
Nice. So we're close to do that. Since this is so simple, we can just add that command on the .travis.yml file. But you think you can think that can be useful add a additional script to test local committed changes? Maybe testing `staged` changes would be nice. Like calling `./test staged` and run tests only for the solutions added or changed.

**Comment by ryukinix** [comment]
Getting staged diff changes is not that hard too, for the simple case is just `git diff --cached`

**Comment by A-Hilaly** [comment]
`git diff master other_branch --name-only ` is pretty good here. but how do we get other_branch name ? maybe we just compare last commit id and last commit in master ?

**Comment by ryukinix** [comment]
> git diff master other_branch --name-only is pretty good here. but how do we get other_branch name ? maybe we just compare last commit id and last commit in master ?

We have all the variables need to do that task correctly on different situations based on the environment variables that travis provide for us, as @lubien pointed earlier.

https://docs.travis-ci.com/user/environment-variables/

```git diff $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST_BRANCH --name-only```

> I suppose calling ./test staged will be calling stats.py/exs 

Yes, sending the correct files from stats.py/exs by the git command above.

> we can just upgradestats.py/exsto make them run like

Of course we can do. This is really an option. By another hand, we will need add twice, on `stats.py` and `stats.exs`. I don't know what is better yet, but I'm really thinking in add a new script (sorry, I know we have a lot). 


> Ill go for a ./test file if its gonna decide which type of tests to run depending on changed/adding files but still we have to implement the --staged-only in stats.py/exs options

I think is unnecessary decide which "type of tests" to run if I understand this correctly. This have a special meaning or just select the correct build system for each language? Because this is already something capable on `stats.py` and `stats.exs` (I believe). The idea of a shell script `test` is having something like that:

[UNTESTED]
```shell
#!/bin/sh

# get the current staged file-names
function staged-files {
    git diff --cached --name-only
}

# get the current file which differs on the master branch 
function diff-master-files {
    git fetch origin # get the last changes from origin/master
    git diff origin/master --name-only
}

BUILD=./stats.py

if [[ $1 == "staged" ]]; then
    staged-files | exec $BUILD
else
    diff-master-files | exec $BUILD
fi
```

Which of course we can implement to treat parameters like `--sync` and `--async` to choose the desired implementation. Will be more like a front-end for the build systems which we've written. That can be more simple to use by new comers, since is more easy to just call `./test staged` before commit or `./test` after commit than figure out how use `stats.py` or `stats.exs`, see what flags I need to use and etc.

**Comment by lubien** [comment]
@ryukinix agreed.

**Comment by A-Hilaly** [comment]
Thank you for clearing up the details, I understand much better now ! 

>  we will need add twice, on stats.py and stats.exs

Its true that we will need to implement it in two different languages and its better make a ./test file. 

>  which "type of tests" to run

What I mean by type of tests is that two types of modification are possible : adds/modification of solutions or modification or stats.py/stats.exs which would require to run all solutions

> since is more easy to just call ./test staged before commit or ./test after commit than figure out how use stats.py or stats.exs, see what flags I need to use and etc.

+1

**Comment by A-Hilaly** [comment]
I am sorry for disappearing, it was a rough week 😩 I want to work in this issue but I want to make sure that nobody has already started working on it !

**Comment by ryukinix** [comment]
Yes, you can work freely on that job. No-ones for know is working with it, personal issues for everyone (University exams mainly).

Thanks for support and contribution on DestructHub. Please open the PR as wish.

**Comment by ryukinix** [comment]
We have a lot of work on #137 by @A-Hilaly almost done. The only thing will be missing is the implementation of `stats.exs` of `--files` flag to receive a list of filepaths to process.

**Comment by ryukinix** [comment]
I'm closing this issue since I talk to @lubien and we have not priority to implement a `stats.exs` version of the differential build, because on travis we need a stable build time to ensure the time is correct. However, currently the `stats.py` doesn't exits when a solution with time bigger than 1min. So we need fix that later to fail the tests for solutions that takes more than 1min as `stats.exs` does.
